name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours
  workflow_dispatch:          # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # important! fetch full history for pushing

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: SuvasishChowdhury
          outputs: dist/snake.svg

      - name: Push Snake Animation to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output   # branch where snake.svg will be stored
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
